/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/seryDwAZMHY
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function SectionLoader() {
  return (
    <div className="w-full h-[400px] bg-[#faedcd] rounded-md flex flex-col items-center justify-center gap-4 p-6">
      <div className="text-3xl font-bold ">Loading Content...</div>
      <p className="text-gray-700">Please wait while we fetch the latest Decorations for you.</p>
      <div className="grid grid-cols-3 gap-8">
        <div className="w-[250px] h-[300px] bg-gray-500 rounded animate-pulse" />
        <div className="w-[250px] h-[300px] bg-gray-500 rounded animate-pulse" />
        <div className="w-[250px] h-[300px] bg-gray-500 rounded animate-pulse" />
      </div>
    </div>
  )
}
