/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Sq5nxkK54gi
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Archivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function AboutUs() {
  return (
    <div className="w-full  dark:bg-gray-800 py-12 md:py-24 lg:py-32">
      <div className="container px-4 md:px-6">
        <div className="grid gap-12 lg:grid-cols-2">
          <div className="space-y-6">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Our Mission</h2>
              <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                At EJevent Decoration, our mission is to provide exceptional decoration services that transform spaces and
                create unforgettable experiences. We believe in the power of creativity and innovation to elevate the
                ambiance and atmosphere of any event or venue.
              </p>
            </div>
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Our Values</h2>
              <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                At the heart of our company are a set of core values that guide our actions and decision-making. We
                believe in delivering exceptional quality, fostering creativity, and providing unparalleled customer
                service. Our team is driven by a passion for transforming spaces and a commitment to making every event
                a memorable one.
              </p>
            </div>
          </div>
          <div className="space-y-6">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Meet Our Designers</h2>
              <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                At EJevent Decoration, we have assembled a talented team of designers who are dedicated to bringing your
                vision to life. Get to know some of the key members of our design team
              </p>
            </div>
          
          </div>
        </div>
      </div>
    </div>
  )
}
