
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/4858E6aGjS5
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"
import { JSX, SVGProps } from "react"
import Image from "next/image"
import { getServices } from "@/server/queries"
import { DecorationCreationDialog, DecorationEditDialog } from "./decoration-dialog"
import { DeleteDecoration } from "./delete-modal"
import { getLocale } from "next-intl/server"

export async function AdminServices() {
   const locale = await getLocale()
   const services = await getServices()
  return (
    <div className="p-4 sm:p-6 md:p-8 lg:p-10">
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-2xl font-bold">Services</h1>
       <DecorationCreationDialog type={'service'}/>

      </div>
      <Card>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Image</TableHead>
              <TableHead>Name</TableHead>
              <TableHead>Description</TableHead>
              {/* <TableHead>Price</TableHead> */}
              <TableHead>Status</TableHead>
              <TableHead>Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
           {/*  <TableRow>
              <TableCell>
                <Image src="/placeholder.svg" alt="Decoration 1" width={80} height={80} className="rounded-md" />
              </TableCell>
              <TableCell>Floral Arch</TableCell>
              <TableCell>A beautiful floral arch perfect for weddings and events.</TableCell>
              <TableCell>$250</TableCell>
              <TableCell>
                <Badge variant="secondary">Available</Badge>
              </TableCell>
              <TableCell>
                <div className="flex items-center gap-2">
                  <Button size="icon" variant="outline">
                    <FilePenIcon className="w-4 h-4" />
                    <span className="sr-only">Edit</span>
                  </Button>
                  <Button size="icon" variant="outline">
                    <TrashIcon className="w-4 h-4" />
                    <span className="sr-only">Delete</span>
                  </Button>
                </div>
              </TableCell>
            </TableRow> */}
          {services.map((service) => (
            <TableRow key={service.id}>
               <TableCell>
                  <Image src={service.images![0]} alt={service.name[locale]} width={80} height={80} className="rounded-md" />
               </TableCell>
               <TableCell>{service.name[locale]}</TableCell>
               <TableCell>{service.description[locale]}</TableCell>
               {/* <TableCell>${service.price}</TableCell> */}
               <TableCell>
                  <Badge variant="secondary">{service.status}</Badge>
               </TableCell>
               <TableCell>
                  <div className="flex items-center gap-2">
                    <DecorationEditDialog decoration={service} />

                    <DeleteDecoration id={service.id} />
                  </div>
               </TableCell>
            </TableRow>
            ))}
          </TableBody>
        </Table>
      </Card>
    </div>
  )
}
