/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/6pGhTslVxSV
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { TooltipProvider, Tooltip, TooltipTrigger, TooltipContent } from "@/components/ui/tooltip"
import { Card, CardHeader, CardTitle, CardContent, CardDescription, CardFooter } from "@/components/ui/card"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"
import { CalendarIcon, CheckIcon, ClockIcon, MountainIcon, XIcon } from "@/lib/icons"
import Image from "next/image"
import { format } from "date-fns"
import { ConfirmBookingDialog } from "./delete-modal"
import { SVGProps } from "react"
interface Props {
  data: {
    id: number;
    user_id: string | null;
    user_name: string;
    user_email: string;
    user_contact: string | null;
    item_id: number;
    item_name: string;
    item_image: string;
    start_at: Date | null;
    end_at: Date | null;
    status: string;
}[]
}
export function AdminHome({data}: Props) {
  const pendings = data.filter(d => d.status === 'pending' ).length ?? 0
  const confirmeds = data.filter(d => d.status === 'confirmed' ).length ?? 0
  const cancelleds = data.filter(d => d.status === 'cancelled' ).length ?? 0
  return (
      <div className="">
        <div className="flex flex-1 flex-col sm:gap-4 sm:py-4 sm:pl-14">
          <main className="grid flex-1 items-start gap-4 p-4 sm:px-6 sm:py-0 md:gap-8">
            <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
              <Card>
                <CardHeader className="flex flex-row items-center justify-between pb-2">
                  <CardTitle className="text-sm font-medium">Total Bookings</CardTitle>
                  <CalendarIcon className="w-4 h-4 text-muted-foreground" />
                </CardHeader>
                <CardContent>
                  <div className="text-2xl font-bold">{data.length ?? 0}</div>
                  <p className="text-xs text-muted-foreground">+20.1% from last month</p>
                </CardContent>
              </Card>
              <Card>
                <CardHeader className="flex flex-row items-center justify-between pb-2">
                  <CardTitle className="text-sm font-medium">Pending Bookings</CardTitle>
                  <ClockIcon className="w-4 h-4 text-muted-foreground" />
                </CardHeader>
                <CardContent>
                  <div className="text-2xl font-bold">{pendings}</div>
                  <p className="text-xs text-muted-foreground">+10.5% from last month</p>
                </CardContent>
              </Card>
              <Card>
                <CardHeader className="flex flex-row items-center justify-between pb-2">
                  <CardTitle className="text-sm font-medium">Confirmed Bookings</CardTitle>
                  <CheckIcon className="w-4 h-4 text-muted-foreground" />
                </CardHeader>
                <CardContent>
                  <div className="text-2xl font-bold">{confirmeds}</div>
                  <p className="text-xs text-muted-foreground">+15% from last month</p>
                </CardContent>
              </Card>
              <Card>
                <CardHeader className="flex flex-row items-center justify-between pb-2">
                  <CardTitle className="text-sm font-medium">Cancelled Bookings</CardTitle>
                  <XIcon className="w-4 h-4 text-muted-foreground" />
                </CardHeader>
                <CardContent>
                  <div className="text-2xl font-bold">{cancelleds}</div>
                  <p className="text-xs text-muted-foreground">-5% from last month</p>
                </CardContent>
              </Card>
            </div>
            <Card>
              <CardHeader className="px-7">
                <CardTitle>Recent Bookings</CardTitle>
                <CardDescription>A list of the most recent bookings for your services.</CardDescription>
              </CardHeader>
              <CardContent>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Customer</TableHead>
                      <TableHead className="hidden sm:table-cell">Service</TableHead>
                      <TableHead className="hidden sm:table-cell">Start Date</TableHead>
                      <TableHead className="hidden sm:table-cell">End Date</TableHead>
                      <TableHead className="hidden md:table-cell">Status</TableHead>
                      <TableHead className="hidden sm:table-cell">image</TableHead>
                      <TableHead className="hidden sm:table-cell">Actions</TableHead>
                      {/* <TableHead className="text-right">Amount</TableHead> */}
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                   {data.map(booking => ( <TableRow key={booking.id}>
                      <TableCell>
                        <div className="font-medium">{booking.user_name}</div>
                        <div className="hidden text-sm text-muted-foreground md:inline">{booking.user_email}</div>
                      </TableCell>
                      <TableCell className="hidden sm:table-cell">{booking.item_name}</TableCell>
                      <TableCell className="hidden sm:table-cell">{format(booking.start_at!, 'yyyy-MM-dd')}</TableCell>
                      <TableCell className="hidden sm:table-cell">{format(booking.end_at!, 'yyyy-MM-dd')}</TableCell>
                      <TableCell className="hidden md:table-cell">
                        <Badge variant="secondary">{booking.status}</Badge>
                      </TableCell>
                      <TableCell className="hidden sm:table-cell"><Image src={ booking.item_image} alt={`image ${booking.item_name}`} width={80} height={80} /></TableCell>
                      {/* <TableCell className="text-right">$250.00</TableCell> */}
                     {booking.status !== 'confirmed' ? <TableCell className="hidden sm:table-cell">{<ConfirmBookingDialog booking={booking} />}</TableCell>: null}
                    </TableRow>
                   ))}
                  </TableBody>
                </Table>
              </CardContent>
              <CardFooter>
                <div className="text-xs text-muted-foreground">
                  Showing <strong>1-10</strong> of <strong>32</strong>
                  bookings
                </div>
              </CardFooter>
            </Card>
          </main>
        </div>
      </div>
    
  )
}
