/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/CgoFdI8wDL1
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Separator } from "@/components/ui/separator"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import Image from "next/image"
import { Drawer, DrawerContent, DrawerTrigger, DrawerHeader, DrawerTitle, DrawerDescription, DrawerFooter, DrawerClose } from "../ui/drawer"

export function BookingConfirmation() {
  return (
    <Drawer >
      <DrawerTrigger asChild>
        <Button variant="outline">View Reservation</Button>
      </DrawerTrigger>
      <DrawerContent className="sm:max-w-[600px]">
      <DrawerHeader>
      <DrawerTitle>Are you absolutely sure?</DrawerTitle>
      <DrawerDescription>This action cannot be undone.</DrawerDescription>
    </DrawerHeader>
        <div className="grid sm:grid-cols-2 grid-cols-1  gap-6">
          <div>
            <Image
              src="/placeholder.svg"
              alt="Decoration Item"
              width={400}
              height={400}
              className="w-full rounded-lg object-cover"
            />
          </div>
          <div className="space-y-4">
            <div>
              <h3 className="text-2xl font-bold">Elegant Floral Arch</h3>
              <p className="text-muted-foreground">Booked for June 15, 2024</p>
            </div>
            <div className="flex items-center justify-between">
              <span className="text-lg font-medium">$500</span>
              <Badge variant="outline">Booked</Badge>
            </div>
            <div className="space-y-2">
              <h4 className="text-lg font-medium">Reservation Details</h4>
              <div className="grid grid-cols-2 gap-2 text-sm">
                <div className="text-muted-foreground">Name:</div>
                <div>John Doe</div>
                <div className="text-muted-foreground">Email:</div>
                <div>john@example.com</div>
                <div className="text-muted-foreground">Phone:</div>
                <div>+1 (555) 555-5555</div>
              </div>
            </div>
          </div>
        </div>
        <Separator className="my-6" />
        <form className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-1">
              <Label htmlFor="name">Name</Label>
              <Input id="name" placeholder="Enter your name" />
            </div>
            <div className="space-y-1">
              <Label htmlFor="email">Email</Label>
              <Input id="email" type="email" placeholder="Enter your email" />
            </div>
          </div>
          <div className="space-y-1">
            <Label htmlFor="phone">Phone</Label>
            <Input id="phone" type="tel" placeholder="Enter your phone number" />
          </div>
          <div className="space-y-1">
            <Label htmlFor="message">Message</Label>
            <Textarea id="message" placeholder="Enter any additional details" />
          </div>
          <DrawerFooter className="flex justify-end gap-2">
            <DrawerClose >Cancel</DrawerClose>
            <Button>Confirm Reservation</Button>
          </DrawerFooter>
        </form>
      </DrawerContent>
    </Drawer>
  )
}
