/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/OVcsrWelWwQ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Caudex } from 'next/font/google'
import { Archivo } from 'next/font/google'

caudex({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { SetStateAction, useState } from "react"
import { Input } from "@/components/ui/input"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"
import {Booking} from "@/utils/types"
import { formatDate } from 'date-fns'
import Image from "next/image"
import { Button } from "../ui/button"
import {useMutation} from "@tanstack/react-query"
import { cancelBooking } from "@/app/actions"
import { toast } from "sonner"

interface BookingsProps {
  bookings: Booking[]

}
export function Bookings({bookings}: BookingsProps) {
  const [search, setSearch] = useState("")
  const [currentPage, setCurrentPage] = useState(1)
  const [bookingsPerPage] = useState(10)
  
  const filteredBookings = bookings.filter((booking) => booking.item_name.toLowerCase().includes(search.toLowerCase()))
  const indexOfLastBooking = currentPage * bookingsPerPage
  const indexOfFirstBooking = indexOfLastBooking - bookingsPerPage
  const currentBookings = filteredBookings.slice(indexOfFirstBooking, indexOfLastBooking)
  const totalPages = Math.ceil(filteredBookings.length / bookingsPerPage)
  const [isLoading, setLoading] = useState(false)
  const handleCancelBooking = async (e: any,id:number) => {
    e.preventDefault()
    setLoading(true)
    const {message} = await cancelBooking(id)
      toast.success(message)
      setLoading(false)
    
  }
  const handlePageChange = (pageNumber: SetStateAction<number>) => {
    setCurrentPage(pageNumber)
  }
  const handleSearch = (e: { target: { value: SetStateAction<string> } }) => {
    setSearch(e.target.value)
    setCurrentPage(1)
  }
  const completedBookings = bookings.filter((booking) => booking.status === "Completed")
  const pendingBookings = bookings.filter((booking) => booking.status === "Pending")
  const cancelledBookings = bookings.filter((booking) => booking.status === "Cancelled")
  const totalBookings = bookings.length
  const totalCompletedBookings = completedBookings.length
  const totalPendingBookings = pendingBookings.length
  const totalCancelledBookings = cancelledBookings.length
  const completedBookingsPercentage = ((totalCompletedBookings / totalBookings) * 100).toFixed(2)
  const pendingBookingsPercentage = ((totalPendingBookings / totalBookings) * 100).toFixed(2)
  const cancelledBookingsPercentage = ((totalCancelledBookings / totalBookings) * 100).toFixed(2)
  return (
    <div className="container mx-auto px-4 py-8 sm:px-6 lg:px-8">
      <div className="mb-6">
        <h1 className="text-2xl font-bold">Bookings History</h1>
      </div>
      <div className="mb-6">
        <Input
          type="text"
          placeholder="Search by decoration name"
          value={search}
          onChange={handleSearch}
          className="w-full max-w-md"
        />
      </div>
      <div className="overflow-x-auto">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>image</TableHead>
              <TableHead>Date</TableHead>
              <TableHead>Start Time</TableHead>
              <TableHead>End Time</TableHead>
              <TableHead>Client Name</TableHead>
              <TableHead>Decoration name</TableHead>
              <TableHead>Status</TableHead>
              <TableHead>Action</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {currentBookings.map((booking) => (
              <TableRow key={booking.id}>
                <TableCell><Image src={booking.item_image ?? '/placeholder.jpg'} alt={booking.item_name} height={100} width={100}/> </TableCell>
                <TableCell>{formatDate(booking.start_at!, 'MM/dd/yyyy')}</TableCell>
                <TableCell>{booking.start_at!.toLocaleTimeString()}</TableCell>
                <TableCell>{booking.end_at!.toLocaleTimeString()}</TableCell>
                <TableCell>{booking.user_name}</TableCell>
                <TableCell>{booking.item_name}</TableCell>
                <TableCell>
                  <div
                    className={`px-2 py-1 rounded-full text-xs font-medium ${
                      booking.status === "Completed"
                        ? "bg-green-100 text-green-800"
                        : booking.status === "Pending"
                        ? "bg-yellow-100 text-yellow-800"
                        : "bg-red-100 text-red-800"
                        }`}
                  >
                    {booking.status}
                  </div>
                </TableCell>
                        <TableCell><Button onClick={e =>  handleCancelBooking} className="bg-red-500">Cancel Reservation</Button></TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
      <div className="mt-6 flex justify-center">
      
      </div>
      <div className="mt-8">
        <h2 className="text-xl font-bold mb-4">Bookings Summary</h2>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          <div className="bg-green-100 text-green-800 p-4 rounded-lg">
            <h3 className="text-lg font-bold mb-2">Completed</h3>
            <p className="text-4xl font-bold">{totalCompletedBookings}</p>
            <p className="text-sm text-muted-foreground">({completedBookingsPercentage}% of total)</p>
          </div>
          <div className="bg-yellow-100 text-yellow-800 p-4 rounded-lg">
            <h3 className="text-lg font-bold mb-2">Pending</h3>
            <p className="text-4xl font-bold">{totalPendingBookings}</p>
            <p className="text-sm text-muted-foreground">({pendingBookingsPercentage}% of total)</p>
          </div>
          <div className="bg-red-100 text-red-800 p-4 rounded-lg">
            <h3 className="text-lg font-bold mb-2">Cancelled</h3>
            <p className="text-4xl font-bold">{totalCancelledBookings}</p>
            <p className="text-sm text-muted-foreground">({cancelledBookingsPercentage}% of total)</p>
          </div>
        </div>
        <div className="mt-8">
          <h2 className="text-xl font-bold mb-4">Total Bookings</h2>
          <p className="text-4xl font-bold">{totalBookings}</p>
        </div>
      </div>
    </div>
  )
}
