
'use client'
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/tUYJcKyB59v
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Baskerville } from 'next/font/google'
import { Cormorant_Garamond } from 'next/font/google'

libre_baskerville({
  subsets: ['latin'],
  display: 'swap',
})

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { toast } from "sonner"


export function ComingSoon() {
  const onPressed= (e: any)=> {
    toast("You will be notify when the site would be available.")
  }
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <main className="flex-1 flex items-center justify-center px-4 md:px-6">
        <div className="max-w-3xl space-y-6 text-center">
          <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">
            Elevate Your Space with Our Upcoming Decoration Reservation Service
          </h1>
          <p className="text-gray-500 md:text-xl dark:text-gray-400">
            Get ready to transform your living or workspace with our cutting-edge decoration reservation platform,
            launching soon. Sign up now to be the first to experience our innovative solutions.
          </p>
          <div className="w-full max-w-md">
            <form className="flex gap-2" >
              <Input type="email" placeholder="Enter your email" className="max-w-lg flex-1" />
              <Button  onClick={onPressed}>Notify Me</Button>
            </form>
          </div>
        </div>
      </main>
      <footer className="px-4 md:px-6 py-6 w-full shrink-0 border-t">
        <p className="text-xs text-gray-500 dark:text-gray-400">&copy; 2024 Decor Reservation. All rights reserved.</p>
      </footer>
    </div>
  )
}
