/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/f6ZvutZg6Rj
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import Card from "./card";

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

import {Decoration} from '@/utils/types'
interface DecorationsProps {
  decorations: Decoration[]
}
export function Decorations({decorations}: DecorationsProps) {
  
  return (
    <section className=" p-4 md:p-6" id="decorations">
      
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-x-4 sm:gap-x-32 gap-y-8">
      {decorations.map((decoration) => ( 
        <Card key={decoration.id} name={decoration.name} description={decoration.description} images={decoration.images} slug={decoration.slug} id={`${decoration.id}`} />
      ))}
  
      </div>
  </section>
  )
}
