/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/QALnGZl2uAH
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Carousel, CarouselContent, CarouselItem, CarouselPrevious, CarouselNext } from "@/components/ui/carousel"
import Image from "next/image"
import { JSX, SVGProps } from "react"

const mockData: GalleryItemProps[] = [
  {image: 'https://firebasestorage.googleapis.com/v0/b/ejevent-ff5c6.appspot.com/o/decorations%2Fdecoration_6.jpg?alt=media&token=f484d62c-538e-40ba-8cf1-5a7c3422c157',
  title: 'Rustic Wall Decor',
  description: 'Handcrafted wooden wall art for a cozy, farmhouse-inspired look.',
  id: 1
  },
  {image: 'https://firebasestorage.googleapis.com/v0/b/ejevent-ff5c6.appspot.com/o/services%2Fdecoration_2.jpg?alt=media&token=24e9d836-1d15-4928-800b-46bc3f5d28b8',
  title: 'Elegant Table Centerpieces',
  description: 'Custom floral arrangements to elevate your dining experience.',
  id: 2
  },
  {image: 'https://firebasestorage.googleapis.com/v0/b/ejevent-ff5c6.appspot.com/o/services%2Fdecoration_3.jpg?alt=media&token=1bb63217-d997-4a13-bcf6-79aafc2e7ac8',
  title: 'Modern Lighting Fixtures',
  description: 'Illuminate your space with sleek, contemporary lighting solutions.',
  id: 3
  },
  {image: 'https://firebasestorage.googleapis.com/v0/b/ejevent-ff5c6.appspot.com/o/decorations%2Fslide.jpg?alt=media&token=bf7195d4-5d17-48d6-8d93-2f09e4ece538',
  title: 'Luxury Home Accents',
  description: 'Add a touch of sophistication with our collection of premium home decor.',
  id: 4
  },
  {image: 'https://firebasestorage.googleapis.com/v0/b/ejevent-ff5c6.appspot.com/o/decorations%2Fdecoration_5.jpg?alt=media&token=0244ab16-6e66-47d1-94fa-4c74a9fe294b',
  title: 'Artisanal Wall Hangings',
  description: 'Handwoven tapestries and macrame pieces to add texture to your walls.',
  id: 5
  },
];

export function Gallery() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container px-4 md:px-6">
        <div className="grid gap-8">
          <div className="grid gap-4">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
              Explore Our Home Decor Collection
            </h2>
            <p className="text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Find the perfect pieces to elevate your living space.
            </p>
          </div>
          <div className="relative group">
            <Carousel className="w-full max-w-4xl mx-auto">
              <CarouselContent>
                {...mockData.map((data)=> <GalleryItem {...data} key={data.id} />)}
               
              </CarouselContent>
              <CarouselPrevious className="absolute top-1/2 left-4 -translate-y-1/2 z-10">
                <ChevronLeftIcon className="w-8 h-8 text-white/70 hover:text-white transition-colors" />
              </CarouselPrevious>
              <CarouselNext className="absolute top-1/2 right-4 -translate-y-1/2 z-10">
                <ChevronRightIcon className="w-8 h-8 text-white/70 hover:text-white transition-colors" />
              </CarouselNext>
            </Carousel>
          </div>
        </div>
      </div>
    </section>
  )
}

function ChevronLeftIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15 18-6-6 6-6" />
    </svg>
  )
}


function ChevronRightIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}

    function GalleryItem({image, title, description}: GalleryItemProps) {
      return (<CarouselItem>
                  <div className="relative overflow-hidden rounded-xl">
                    <Image src={image} width={1200} height={800} alt="Rustic Wall Decor" className="object-cover w-full aspect-[3/2]" />
                    <div className="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent" />
                    <div className="absolute bottom-0 left-0 p-4 text-white">
                      <h3 className="text-lg font-semibold">{title}</h3>
                      <p className="text-sm">{description}.</p>
                    </div>
                  </div>
                </CarouselItem>);
    }
  

interface GalleryItemProps {
  image: string,
  title: string,
  description: string,
  id: number
}