/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/QALnGZl2uAH
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
'use client'
import { Carousel, CarouselContent, CarouselItem, CarouselPrevious, CarouselNext } from "@/components/ui/carousel"
import { getGalleryItems } from "@/server/queries"
import Image from "next/image"
import { JSX, SVGProps } from "react"
import Autoplay from "embla-carousel-autoplay";
import { useRef } from "react";
import { GalleryItemInterface } from "@/utils/types"
import { Card } from "../ui/card"
interface Props {
  items :  GalleryItemInterface[]
}
export  function Gallery({items}: Props) {
  const galleryData = items
  const plugin = useRef(
    Autoplay({ delay: 2000, stopOnInteraction: true })
  )
  return (
    <section className="w-full py-6  md:py-24 lg:py-32 bg-[#fefae0]">
      <div className="container px-4 w-full md:px-6">
        <div className="grid gap-4">
          <div className="grid gap-4">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
              Explore Our Decor Collection
            </h2>
            <p className="text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
            Transform your special occasions into unforgettable experiences with our exquisite decorations and event planning services. From stunning centerpieces to breathtaking backdrops, we'll bring your vision to life with style and elegance. Let us help you create magical moments that will leave a lasting impression on your guests. Explore our collection and let's make your next event truly extraordinary
            </p>
          </div>
          <div className="w-full flex  justify-center">
            <Carousel className="w-full max-w-xs md:max-w-xl lg:max-w-4xl"  opts={{
        align: "start", 
      }} plugins={[plugin.current]}>
              <CarouselContent className="flex w-full aspect-square items-center justify-center ">
                {...galleryData.map((data,i)=> <GalleryItem  {...data} key={i}  />)}

              </CarouselContent>
            </Carousel>
          </div>
        </div>
      </div>
    </section>
  )
}


function GalleryItem({image, title, description}: GalleryItemProps) {
  return (<CarouselItem className=" md:basis-1/2   lg:basis-1/3 w-full">
              <Card  className="relative overflow-hidden w-full h-96  rounded-xl">
                <Image src={image}   layout='fill' objectFit='cover' alt="Rustic Wall Decor" className="" />
                <div className="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent" />
                <div className="absolute bottom-0 left-0 p-4 text-white">
                  <h3 className="text-lg font-semibold">{title}</h3>
                  <p className="text-sm line-clamp-3  ">{description}.</p>
                </div>
              </Card>
            </CarouselItem>);
}

function ChevronLeftIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15 18-6-6 6-6" />
    </svg>
  )
}


function ChevronRightIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}

interface GalleryItemProps {
  image: string,
  title: string,
  description: string,
  id: number
}