/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/QALnGZl2uAH
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Carousel, CarouselContent, CarouselItem, CarouselPrevious, CarouselNext } from "@/components/ui/carousel"
import { getGalleryItems } from "@/server/queries"
import Image from "next/image"
import { JSX, SVGProps } from "react"



export async function Gallery() {
  const galleryData = await getGalleryItems()
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container px-4 md:px-6">
        <div className="grid gap-8">
          <div className="grid gap-4">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
              Explore Our Home Decor Collection
            </h2>
            <p className="text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Find the perfect pieces to elevate your living space.
            </p>
          </div>
          <div className="relative group">
            <Carousel className="w-full max-w-4xl mx-auto">
              <CarouselContent>
                {...galleryData.map((data)=> <GalleryItem {...data} key={data.id} />)}
               
              </CarouselContent>
              <CarouselPrevious className="absolute top-1/2 left-4 -translate-y-1/2 z-10">
                <ChevronLeftIcon className="w-8 h-8 text-white/70 hover:text-white transition-colors" />
              </CarouselPrevious>
              <CarouselNext className="absolute top-1/2 right-4 -translate-y-1/2 z-10">
                <ChevronRightIcon className="w-8 h-8 text-white/70 hover:text-white transition-colors" />
              </CarouselNext>
            </Carousel>
          </div>
        </div>
      </div>
    </section>
  )
}

function ChevronLeftIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15 18-6-6 6-6" />
    </svg>
  )
}


function ChevronRightIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}

    function GalleryItem({image, title, description}: GalleryItemProps) {
      return (<CarouselItem>
                  <div className="relative overflow-hidden rounded-xl">
                    <Image src={image} width={1200} height={800} alt="Rustic Wall Decor" className="object-cover w-full aspect-[3/2]" />
                    <div className="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent" />
                    <div className="absolute bottom-0 left-0 p-4 text-white">
                      <h3 className="text-lg font-semibold">{title}</h3>
                      <p className="text-sm">{description}.</p>
                    </div>
                  </div>
                </CarouselItem>);
    }
  

interface GalleryItemProps {
  image: string,
  title: string,
  description: string,
  id: number
}