/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/f6ZvutZg6Rj
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/


/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

import { useLocale } from "next-intl";
import Card from "./card";
import { Decoration} from "@/utils/types"

interface ServicesProps {
  services: Decoration[],
  title: string
  description: string
}


export function Services({services, title, description}: ServicesProps) {
   const local = useLocale()
  return (
    <section className=" p-4 md:p-6">

    <div className="flex flex-col items-center justify-center space-y-4 text-center mb-16 ">
      <div className="space-y-2">
        <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">{title}</h2>
        <p className="max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
        {description}
        </p>
      </div>
    </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-3 place-items-center gap-x-4 sm:gap-x-32 gap-y-8">
    {services.map((service) => (
      <Card key={service.id} name={service.name[local]} images={service.images!.slice(0,3)} slug={service.slug} id={`${service.id}`} description={service.description[local]}/>
    ))}
      </div>
    </section>
  )
}
