/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Sm5JdhblyID
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Collapsible, CollapsibleTrigger, CollapsibleContent } from "@/components/ui/collapsible"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Switch } from "@/components/ui/switch"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Slider } from "@/components/ui/slider"
import { Button } from "@/components/ui/button"
import { JSX, SVGProps } from "react"


export function Settings() {
  return (
    <div className="flex flex-col w-full min-h-screen bg-muted/40">
      <main className="flex min-h-[calc(100vh_-_theme(spacing.16))] flex-1 flex-col gap-8 p-4 md:gap-12 md:p-10">
        <div className="max-w-6xl w-full mx-auto">
          <h1 className="font-semibold text-3xl">Settings</h1>
        </div>
        <div className="grid gap-6 max-w-6xl w-full mx-auto">
          <Collapsible>
            <CollapsibleTrigger className="flex items-center justify-between rounded-md bg-card p-4 text-card-foreground transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">
              <div className="flex items-center gap-4">
                <UserIcon className="h-6 w-6" />
                <h3 className="text-lg font-semibold">Account</h3>
              </div>
              <ChevronRightIcon className="h-5 w-5 transition-all [data-state=open]:rotate-90" />
            </CollapsibleTrigger>
            <CollapsibleContent className="grid gap-4 p-4">
              <div className="grid gap-2">
                <Label htmlFor="name">Name</Label>
                <Input id="name" placeholder="Your name" />
                <div className="text-sm text-muted-foreground">
                  This is the name that will be displayed on your profile.
                </div>
              </div>
              <div className="grid gap-2">
                <Label htmlFor="email">Email</Label>
                <Input id="email" type="email" placeholder="Your email" />
                <div className="text-sm text-muted-foreground">This is the email associated with your account.</div>
              </div>
              <div className="grid gap-2">
                <Label htmlFor="password">Password</Label>
                <Input id="password" type="password" placeholder="Your password" />
                <div className="text-sm text-muted-foreground">Change your password to secure your account.</div>
              </div>
            </CollapsibleContent>
          </Collapsible>
          <Collapsible>
            <CollapsibleTrigger className="flex items-center justify-between rounded-md bg-card p-4 text-card-foreground transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">
              <div className="flex items-center gap-4">
                <BellIcon className="h-6 w-6" />
                <h3 className="text-lg font-semibold">Notifications</h3>
              </div>
              <ChevronRightIcon className="h-5 w-5 transition-all [data-state=open]:rotate-90" />
            </CollapsibleTrigger>
            <CollapsibleContent className="grid gap-4 p-4">
              <div className="grid gap-2">
                <Label htmlFor="email-notifications">Email Notifications</Label>
                <Switch id="email-notifications" />
                <div className="text-sm text-muted-foreground">
                  Receive email notifications for new bookings and updates.
                </div>
              </div>
              <div className="grid gap-2">
                <Label htmlFor="push-notifications">Push Notifications</Label>
                <Switch id="push-notifications" />
                <div className="text-sm text-muted-foreground">
                  Receive push notifications for new bookings and updates.
                </div>
              </div>
            </CollapsibleContent>
          </Collapsible>
          <Collapsible>
            <CollapsibleTrigger className="flex items-center justify-between rounded-md bg-card p-4 text-card-foreground transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">
              <div className="flex items-center gap-4">
                <PaletteIcon className="h-6 w-6" />
                <h3 className="text-lg font-semibold">Appearance</h3>
              </div>
              <ChevronRightIcon className="h-5 w-5 transition-all [data-state=open]:rotate-90" />
            </CollapsibleTrigger>
            <CollapsibleContent className="grid gap-4 p-4">
              <div className="grid gap-2">
                <Label htmlFor="theme">Theme</Label>
                <Select  defaultValue="light">
                  <SelectTrigger>
                    <SelectValue placeholder="Select theme" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="light">Light</SelectItem>
                    <SelectItem value="dark">Dark</SelectItem>
                    <SelectItem value="system">System</SelectItem>
                  </SelectContent>
                </Select>
                <div className="text-sm text-muted-foreground">Choose the color theme for the dashboard.</div>
              </div>
              <div className="grid gap-2">
                <Label htmlFor="font-size">Font Size</Label>
                <Slider id="font-size" defaultValue={[16]} min={12} max={20} step={2} />
                <div className="text-sm text-muted-foreground">Adjust the font size for better readability.</div>
              </div>
            </CollapsibleContent>
          </Collapsible>
          <Collapsible>
            <CollapsibleTrigger className="flex items-center justify-between rounded-md bg-card p-4 text-card-foreground transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">
              <div className="flex items-center gap-4">
                <LockIcon className="h-6 w-6" />
                <h3 className="text-lg font-semibold">Security</h3>
              </div>
              <ChevronRightIcon className="h-5 w-5 transition-all [data-state=open]:rotate-90" />
            </CollapsibleTrigger>
            <CollapsibleContent className="grid gap-4 p-4">
              <div className="grid gap-2">
                <Label htmlFor="two-factor-auth">Two-Factor Authentication</Label>
                <Switch id="two-factor-auth" />
                <div className="text-sm text-muted-foreground">
                  Enhance the security of your account with two-factor authentication.
                </div>
              </div>
              <div className="grid gap-2">
                <Label htmlFor="login-history">Login History</Label>
                <Button variant="outline" size="sm">
                  View Login History
                </Button>
                <div className="text-sm text-muted-foreground">Review your recent login activity.</div>
              </div>
            </CollapsibleContent>
          </Collapsible>
        </div>
      </main>
    </div>
  )
}

function BellIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9" />
      <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0" />
    </svg>
  )
}


function ChevronRightIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}


function LockIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="11" x="3" y="11" rx="2" ry="2" />
      <path d="M7 11V7a5 5 0 0 1 10 0v4" />
    </svg>
  )
}


function PaletteIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="13.5" cy="6.5" r=".5" fill="currentColor" />
      <circle cx="17.5" cy="10.5" r=".5" fill="currentColor" />
      <circle cx="8.5" cy="7.5" r=".5" fill="currentColor" />
      <circle cx="6.5" cy="12.5" r=".5" fill="currentColor" />
      <path d="M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10c.926 0 1.648-.746 1.648-1.688 0-.437-.18-.835-.437-1.125-.29-.289-.438-.652-.438-1.125a1.64 1.64 0 0 1 1.668-1.668h1.996c3.051 0 5.555-2.503 5.555-5.554C21.965 6.012 17.461 2 12 2z" />
    </svg>
  )
}


function UserIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}
